import { cn } from '@/lib/utils';
import { Theme } from '@radix-ui/themes';

import './globals.css';
import '@radix-ui/themes/styles.css';

import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
