import { cn } from '@/libs/utils';
import { Theme } from '@radix-ui/themes';

import './globals.css';
import '@radix-ui/themes/styles.css';

import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { authOptions } from '@/libs/auth/auth-options';
import NextAuthProvider from '@/libs/providers/next-auth-provider';
import { ReactQueryProvider } from '@/libs/providers/react-query-provider';
import { getServerSession } from 'next-auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <NextAuthProvider>
          <ReactQueryProvider session={session}>
            <Theme>{children}</Theme>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
